#
# setup certbot
#
- name: enable repos
  command: "yum-config-manager --enable {{ item }}"
  with_items: "{{ certbot_repos }}"
  tags:
    - certbot
    - certbot_setup

- name: install certbot dependencies
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ certbot_dependencies }}"
  tags:
    - certbot
    - certbot_setup

- name: install certbot
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ certbot_packages }}"
  tags:
    - certbot
    - certbot_setup

- name: run certbot
  shell: certbot --nginx certonly -d {{ item }} --noninteractive --agree-tos --email {{ certbot_email }}
  with_items: "{{ certbot_sites[inventory_hostname] | default([]) }}"
  tags:
    - certbot
    - certbot_generate

- name: create certbot cron
  cron:
    name: certbot renew
    minute: 0
    hour: 0,12
    job: "certbot renew --noninteractive --post-hook 'systemctl restart nginx'"
  tags:
    - certbot
    - certbot_setup

# TODO: need refine: https://github.com/certbot/certbot/issues/4937
- name: fix for certbot cron cannot find nginx binary
  file:
    src: /usr/sbin/nginx
    dest: /usr/bin/nginx
    state: link
  ignore_errors: yes
  tags:
    - certbot
    - certbot_setup
